// // <auto-generated />
// using System;
// using ImobDLApi.Context;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Metadata;
// using Microsoft.EntityFrameworkCore.Migrations;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

// #nullable disable

// namespace ImobDLApi.Migrations
// {
//     [DbContext(typeof(ImobDLContext))]
//     [Migration("20230322130418_PhotoMigration")]
//     partial class PhotoMigration
//     {
//         protected override void BuildTargetModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("ProductVersion", "6.0.13")
//                 .HasAnnotation("Relational:MaxIdentifierLength", 128);

//             SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//             modelBuilder.Entity("ImobDLApi.models.Bairro", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                     b.Property<int>("CidadeId")
//                         .HasColumnType("int");

//                     b.Property<string>("Nome")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("Id");

//                     b.HasIndex("CidadeId");

//                     b.ToTable("Bairros");
//                 });

//             modelBuilder.Entity("ImobDLApi.models.Cidade", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                     b.Property<string>("CidadeNome")
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("Id");

//                     b.ToTable("Cidades");
//                 });

//             modelBuilder.Entity("ImobDLApi.models.Image", b =>
//                 {
//                     b.Property<string>("Id")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<Guid>("ImovelId")
//                         .HasColumnType("uniqueidentifier");

//                     b.Property<bool>("IsMain")
//                         .HasColumnType("bit");

//                     b.Property<string>("Url")
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("Id");

//                     b.HasIndex("ImovelId");

//                     b.ToTable("Images");
//                 });

//             modelBuilder.Entity("ImobDLApi.models.Imovel", b =>
//                 {
//                     b.Property<Guid>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("uniqueidentifier");

//                     b.Property<int>("BairroId")
//                         .HasColumnType("int");

//                     b.Property<int>("Banheiros")
//                         .HasColumnType("int");

//                     b.Property<string>("CEP")
//                         .IsRequired()
//                         .HasMaxLength(9)
//                         .HasColumnType("nvarchar(9)");

//                     b.Property<string>("Descricao")
//                         .IsRequired()
//                         .HasMaxLength(300)
//                         .HasColumnType("nvarchar(300)");

//                     b.Property<bool>("EVenda")
//                         .HasColumnType("bit");

//                     b.Property<int>("Garagens")
//                         .HasColumnType("int");

//                     b.Property<string>("Nome")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int>("Numero")
//                         .HasColumnType("int");

//                     b.Property<int?>("NumeroDoApCd")
//                         .HasColumnType("int");

//                     b.Property<decimal>("Preco")
//                         .HasColumnType("decimal(10,2)");

//                     b.Property<int>("Quartos")
//                         .HasColumnType("int");

//                     b.Property<string>("Rua")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int>("Salas")
//                         .HasColumnType("int");

//                     b.Property<int>("TipoId")
//                         .HasColumnType("int");

//                     b.HasKey("Id");

//                     b.HasIndex("BairroId");

//                     b.HasIndex("TipoId");

//                     b.ToTable("Imoveis");
//                 });

//             modelBuilder.Entity("ImobDLApi.models.Tipo", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                     b.Property<string>("TipoDescricao")
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("Id");

//                     b.ToTable("Tipos");
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                 {
//                     b.Property<string>("Id")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("ConcurrencyStamp")
//                         .IsConcurrencyToken()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Name")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<string>("NormalizedName")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.HasKey("Id");

//                     b.HasIndex("NormalizedName")
//                         .IsUnique()
//                         .HasDatabaseName("RoleNameIndex")
//                         .HasFilter("[NormalizedName] IS NOT NULL");

//                     b.ToTable("AspNetRoles", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                     b.Property<string>("ClaimType")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("ClaimValue")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("RoleId")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("Id");

//                     b.HasIndex("RoleId");

//                     b.ToTable("AspNetRoleClaims", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
//                 {
//                     b.Property<string>("Id")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<int>("AccessFailedCount")
//                         .HasColumnType("int");

//                     b.Property<string>("ConcurrencyStamp")
//                         .IsConcurrencyToken()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Email")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<bool>("EmailConfirmed")
//                         .HasColumnType("bit");

//                     b.Property<bool>("LockoutEnabled")
//                         .HasColumnType("bit");

//                     b.Property<DateTimeOffset?>("LockoutEnd")
//                         .HasColumnType("datetimeoffset");

//                     b.Property<string>("NormalizedEmail")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<string>("NormalizedUserName")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<string>("PasswordHash")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("PhoneNumber")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<bool>("PhoneNumberConfirmed")
//                         .HasColumnType("bit");

//                     b.Property<string>("SecurityStamp")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<bool>("TwoFactorEnabled")
//                         .HasColumnType("bit");

//                     b.Property<string>("UserName")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.HasKey("Id");

//                     b.HasIndex("NormalizedEmail")
//                         .HasDatabaseName("EmailIndex");

//                     b.HasIndex("NormalizedUserName")
//                         .IsUnique()
//                         .HasDatabaseName("UserNameIndex")
//                         .HasFilter("[NormalizedUserName] IS NOT NULL");

//                     b.ToTable("AspNetUsers", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                     b.Property<string>("ClaimType")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("ClaimValue")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("UserId")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("Id");

//                     b.HasIndex("UserId");

//                     b.ToTable("AspNetUserClaims", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                 {
//                     b.Property<string>("LoginProvider")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("ProviderKey")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("ProviderDisplayName")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("UserId")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("LoginProvider", "ProviderKey");

//                     b.HasIndex("UserId");

//                     b.ToTable("AspNetUserLogins", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                 {
//                     b.Property<string>("UserId")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("RoleId")
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("UserId", "RoleId");

//                     b.HasIndex("RoleId");

//                     b.ToTable("AspNetUserRoles", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                 {
//                     b.Property<string>("UserId")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("LoginProvider")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("Name")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("Value")
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("UserId", "LoginProvider", "Name");

//                     b.ToTable("AspNetUserTokens", (string)null);
//                 });

//             modelBuilder.Entity("ImobDLApi.models.Bairro", b =>
//                 {
//                     b.HasOne("ImobDLApi.models.Cidade", "Cidade")
//                         .WithMany("Bairros")
//                         .HasForeignKey("CidadeId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("Cidade");
//                 });

//             modelBuilder.Entity("ImobDLApi.models.Image", b =>
//                 {
//                     b.HasOne("ImobDLApi.models.Imovel", "Imovel")
//                         .WithMany()
//                         .HasForeignKey("ImovelId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("Imovel");
//                 });

//             modelBuilder.Entity("ImobDLApi.models.Imovel", b =>
//                 {
//                     b.HasOne("ImobDLApi.models.Bairro", "Bairro")
//                         .WithMany()
//                         .HasForeignKey("BairroId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("ImobDLApi.models.Tipo", "Tipo")
//                         .WithMany()
//                         .HasForeignKey("TipoId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("Bairro");

//                     b.Navigation("Tipo");
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                         .WithMany()
//                         .HasForeignKey("RoleId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                         .WithMany()
//                         .HasForeignKey("RoleId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("ImobDLApi.models.Cidade", b =>
//                 {
//                     b.Navigation("Bairros");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
